### ISSUE TITLE
https://github.com/erja/pilvi/blob/master/w3%20NodeJS/01%20Introduction/membership.js

### ISSUE THREAD

**Issue by erja** [erja/pilvi#5]
Debugger listening on [::]:15454
module.js:471
    throw err;
    ^

Error: Cannot find module 'readline-sync'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/w3 NodeJS/01 Introduction/membership.js:4:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by erja** [comment]
OK, no problem anymore.
